### PR TITLE
Feature/dockerize

### PR DESCRIPTION
**Pull request by zacck-zz**
## Changes Proposed 

- [x] Add a docker set up for the application

### CODE REVIEW

**Comment by zacck-zz** [comment]
@omanimo @Pancakem please review this for me, so we can push towards all the services packages

**Review by Pancakem — APPROVED** [review]
Looks good to me. @zacck

**Comment by omanimo** [comment]
Added an install command for pipenv on dockerfile.

**Review by omanimo — COMMENTED** [review]
Reviewed and made some modifications

**Comment by Pancakem** [comment]
Hey @omanimo we no longer use `pipenv` we are using `pip` with the `requirements.txt` file.

**Comment by omanimo** [comment]
Ooh I need to update myself on this. Thanks @Pancakem

**Pull request merged**
